image:
  repository: scalecube/spinless
  tag: develop
  pullPolicy: Always

env:
  timestamp: 111111
  TILLER_NAMESPACE: tiller

podTemplate:
  annotations: {}

  labels: {}

nodeSelector:
  environment: dev

service:
  internalPort: 5000
  annotations: {}
  type: NodePort

ingress:
  dnsname: scalecube-spinless

storageClassName: aws-reclaimdel
