apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name | quote }}
      annotations:
    spec:
      serviceAccount: scalecube-spinless
      serviceAccountName: scalecube-spinless
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{- range $pkey, $pval := .Values.env }}
        - name: {{ $pkey }}
          value: {{ $pval | quote }}
{{- end }}
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              name: vault-config
              key: VAULT_ADDR
        - name: VAULT_ROLE
          valueFrom:
            configMapKeyRef:
              name: vault-config
              key: VAULT_ROLE
        - name: VAULT_SECRETS_PATH
          valueFrom:
            configMapKeyRef:
              name: vault-config
              key: VAULT_SECRETS_PATH
        ports:
        - name: port-{{ .Values.service.internalPort | toString }}
          containerPort: {{ .Values.service.internalPort }}
        volumeMounts:
          - name: spinless-state-volume
            mountPath: /opt/state
      volumes:
        - name: spinless-state-volume
          persistentVolumeClaim:
            claimName: state-volume-claim
      tolerations:
        - effect: NoSchedule
          key: type
          operator: Equal
          value: kubsystem
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300

