kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  name: state-volume-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: "spinless"
    service: "spinless"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.storageClassName }}