apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: scalecube-spinless
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.dnsname }}`)
    services:
    - name: scalecube-spinless-service
      port: 5000
